production:
  website: http://diamondresidential.codeifier.com
  image_directory: /home/deployment/sites/diamondresidential/wp-content/uploads
  portals:
    zoopla:
      username: diamond
      password: tpFqD9qd56R7
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: DiamondRes
      password:  d94xfhj2
      branch_id: 51272
      url: ftp.primelocation.com

development:
  website: http://local.diamondresidential.co.uk
  image_directory: /var/www/diamond-residential/wp-content/uploads
  portals:
    zoopla:
      username: diamond
      password: tpFqD9qd56R7
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: DiamondRes
      password: d94xfhj2
      branch_id: 51272
      url: ftp.primelocation.com
